/*
* generated by Xtext
*/
package dsl.group;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GroupStandaloneSetup extends GroupStandaloneSetupGenerated{

	public static void doSetup() {
		new GroupStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

