/*
 * generated by Xtext
 */
package dsl.group;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GroupRuntimeModule extends dsl.group.AbstractGroupRuntimeModule {

}
