/*
 * generated by Xtext
 */
package dsl.entity.ui.contentassist

import dsl.entity.ui.contentassist.AbstractEntityProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntityProposalProvider extends AbstractEntityProposalProvider {
}
