/*
 * generated by Xtext
 */
package dsl.group.ui.contentassist

import dsl.group.ui.contentassist.AbstractGroupProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GroupProposalProvider extends AbstractGroupProposalProvider {
}
