/*
 * generated by Xtext
 */
package dsl.entity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityRuntimeModule extends dsl.entity.AbstractEntityRuntimeModule {

}
