/*
 * generated by Xtext
 */
package dsl.group.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GroupUiModule extends dsl.group.ui.AbstractGroupUiModule {
	public GroupUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
